<head><title>Query 2</title></head>
<body>
<?php


	//open a connection to dbase server 
	include 'open.php';


	ini_set('error_reporting', E_ALL);
	ini_set('display_errors', true);

	//Collect the posted value in a variable called $item
	$country = $_POST['country'];

	// echo some basic header info onto the page
	echo "<h2>Show the average number of daily new confirmed Covid-19 cases in $country between January 2021 and May 2021?</h2><br>";

	//Determine if any input was actually collected
	if (empty($country)) {
		echo "empty <br><br>";
	
	} else {
	
		echo $country."<br><br>";
	

		if ($stmt = $conn->prepare("CALL Query_2(?)")) {
	

		$stmt->bind_param("s", $country);
	
		//Run the actual query
		if ($stmt->execute()) {
	
			//Store result set generated by the prepared statement
			$result = $stmt->get_result();
	
			if (($result) && ($result->num_rows != 0)) {
		
				//Create table to display results
				echo "<table border=\"1px solid black\">";
				echo "<tr><th> Average newly confirmed Covid-19 cases </th></tr>";
	
				//Report result set by visiting each row in it
				while ($row = $result->fetch_row()) {
					echo "<tr>";
					echo "<td>".$row[0]."</td>";
					echo "</tr>";
				} 
			
		
				echo "</table>";
				
			}	else {

				echo "No record found for the specified country";
	
			}
	
			//We are done with the result set returned above, so free it
			$result->free_result();
		
		} else {

			echo "Execute failed.<br>";
		}
	
		//Close down the prepared statement
		$stmt->close();
	
		} else {

		echo "Prepare failed.<br>";
		$error = $conn->errno . ' ' . $conn->error;
		echo $error; 
		}
	
	}
	
	$conn->close();
?>
</body>