<head><title>Query 6</title></head>
<body>
<?php


	//open a connection to dbase server 
	include 'open.php';


	ini_set('error_reporting', E_ALL);
	ini_set('display_errors', true);

	$financial_type = $_POST['financial_type'];

        echo "<h2>Show what was the total '$financial_type' of Netflix in the first two quarters of 2020
        </h2><br>";
	if (empty($financial_type)) {
		echo "empty <br><br>";
	
	} else {
	
		echo $financial_type."<br><br>";
	

		if ($stmt = $conn->prepare("CALL Query_6(?)")) {
	

		$stmt->bind_param("s", $financial_type);
	
		//Run the actual query
		if ($stmt->execute()) {
	
			//Store result set generated by the prepared statement
			$result = $stmt->get_result();
	
			if (($result) && ($result->num_rows != 0)) {
		
				//Create table to display results
				echo "<table border=\"1px solid black\">";
				echo "<tr><th> '$financial_type' </th></tr>";
	
				//Report result set by visiting each row in it
				while ($row = $result->fetch_row()) {
					echo "<tr>";
					echo "<td>".$row[0]."</td>";
					echo "</tr>";
				} 
			
		
				echo "</table>";
				
			}	else {
				echo "No record found";
	
			}
	
			$result->free_result();
		
		} else {

			echo "Execute failed.<br>";
		}
	
		$stmt->close();
	
		} else {

		echo "Prepare failed.<br>";
		$error = $conn->errno . ' ' . $conn->error;
		echo $error; 
		}
	
	}
	
	$conn->close();






?>
</body>

